# Generated by Django 5.2.9 on 2026-03-04 00:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CCFUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("new_count", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
                ("unchanged_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("error_details", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("dot_number", models.CharField(db_index=True, max_length=32)),
                ("legal_name", models.CharField(max_length=255)),
                (
                    "safety_rating",
                    models.CharField(
                        choices=[
                            ("Satisfactory", "Satisfactory"),
                            ("Conditional", "Conditional"),
                            ("Unsatisfactory", "Unsatisfactory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("out_of_service_pct", models.FloatField()),
                ("crash_total", models.IntegerField()),
                ("driver_oos_pct", models.FloatField()),
                ("insurance_on_file", models.BooleanField()),
                (
                    "authority_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Revoked", "Revoked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_inspection_date", models.DateField()),
                ("fleet_size", models.IntegerField(default=1)),
                ("score", models.FloatField(db_index=True, default=0.0)),
                ("score_breakdown", models.JSONField(default=dict)),
                ("record_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-score"],
                "indexes": [
                    models.Index(
                        fields=["-score"], name="scoring_car_score_975f2f_idx"
                    ),
                    models.Index(
                        fields=["authority_status"],
                        name="scoring_car_authori_46c585_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoreHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("score_breakdown", models.JSONField(default=dict)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_history",
                        to="scoring.carrier",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
            },
        ),
    ]
